rust/examples/many.rs
rust/src/adapter/mod.rs
rust/tests/README.md
rust/tests/integration_tests.rs
rust/tests/many_tests.rs
rust/tests/otel_json_tests.rs
rust/tests/tests/helpers/mod.rs
rust/tests/tests/helpers/otel_json.rs

This test runner uses executes the examples and checks their output. This lets us be clearer about what specifically failed in the test output.
Downsides:
- Highly coupled to the examples and the test module, if any of those change it'll break the test
- Parsing the output can get annoying
Upsides:
- Fully tests the adapters and modules

feat: Integration test runner that tests the examples

---

rust/src/adapter/otel_formatter/mod.rs

When the otel_formatter has a span with a `None` `parent_span_id` that should be serialized as an empty string instead of None.
This was brought up in the DataDog PR: https://github.com/dylibso/observe-sdk/pull/16#pullrequestreview-1482255353

fix: otel_formatter's parent_span_id None should be serialized as an empty string

---

rust/src/lib.rs
rust/src/version.rs

Follows how it was done for Go.
For now observe-sdk tolerates the version information not being present.

feat: add version checking to rust sdk

---

README.md

Primarily adds the table below, but also some additional information about the repo. Will keep this table updated as we include broader support.
| Language | Runtime SDKs | Adapters |
| -------- | ------------ | -------- |
| Rust | [Wasmtime](/rust) | [Datadog](/rust/src/adapter/datadog.rs), [OpenTelemetry (STDOUT)](/rust/src/adapter/otelstdout.rs), [Zipkin](/rust/src/adapter/zipkin.rs) |
| Go | [Wazero](/go) | [Datadog](/go/adapter/datadog/), [OpenTelemetry (STDOUT)](/go/adapter/otel_stdout/) |

chore: add support table to readme

---

go/adapter.go
go/adapter/datadog/adapter.go
go/adapter/datadog_formatter/format.go
go/bin/datadog/main.go
go/trace_ctx.go

Partially addresses #40
We need a generic way to set the adapter specific metadata like we do in Rust.

feat: Add ability to set adapter scoped metadata

---

rust/src/adapter/zipkin.rs
rust/src/context.rs
rust/tests/many_tests.rs
rust/tests/otel_json_tests.rs

I think the allocation should only ever be recorded as part of a function call event, not standlone. In the case prior to this commit, we actually collect the allocation as part of the function call (e.g. `sbrk`) and _also_ on its own, sent the allocation event along.

fix: memory allocation events should only be sent attached to function calls

---

.github/workflows/ci.yml

checks for correct number of traced memory allocations in an executed test module within Node and Deno runtimes.

ci: add js sdk tests

---

demo-iota/README.md

@bhelx - just to confirm, I think we mean the name of the wasm module stored to disk? Since these are only WASI Command modules, its always calling `_start`, right? 
only clarifying here so that in the future if we do support calling an export function name, then there's no confusion.

chore: demo readme update

---

demo-iota/go/main.go
demo-iota/rust/Cargo.lock
demo-iota/rust/Cargo.toml
demo-iota/rust/src/main.rs

I think it makes a bit more sense to just return the raw bytes from the module response to the http response body rather than assuming we want json. this opens us up to different content types like html, images, etc.

feat(iota): Pass response as raw bytes

---

js/src/lib/parser/mod.ts

Wrapping most of it with a try catch created an unfortunate diff.
This improves the reliability and accuracy of the name parsing:
1. Reads the name subsection id as a byte so ids `>= 128` are supported.
2. Wraps `nameSectionView` accesses with `try...catch` so out of bound accesses  (`RangeError`) will just cease parsing of name section and return the names with successfully parsed before that point.
3. Only reads up to `nameMapLength.value` names from a subsection instead of relying it the namemap going until the end of the subsection. If there's leftover bytes in a subsection, they are skipped, and a warning is logged.

fix: js name parsing - reading subsection ids >= 128 and error handling

---

go/adapter.go

Pretty sure this is just leftover, but it may mislead other implementations to use something other than a `time.Duration` in Go for the interval.

chore: remove unused adapter config struct

---

demo-iota/rust/Dockerfile

Should fix the rust iota builds/deployments by installing protoc in the Dockerfile

fix: install protoc in rust iota dockerfile

---

README.md

Using --fail will print an error message if the status-code is one of the 4xx, 5xx variety.

docs: Add --fail to curl command

---

go/wasm.go
rust/src/adapter/otelstdout.rs
rust/src/wasm_instr.rs

Fixes issue when modules without any version compatibility information from the compiler are parsed.
Additionally only prints trace output in the Rust `otel-stdout` example if there are any spans to format.

fix: parse modules with no compat versions

---

rust/examples/honeycomb.rs
rust/src/adapter/datadog.rs
rust/src/adapter/datadog_formatter/mod.rs
rust/src/adapter/honeycomb.rs
rust/src/adapter/lightstep.rs
rust/src/adapter/mod.rs
rust/src/adapter/otelstdout.rs
rust/src/adapter/zipkin.rs
rust/src/context.rs

- Give base Adapter trait the ability to construct OTEL call spans (since this is industry standard and most common format)
- Hoist (and sum) memory allocations to parent span when current span is being filtered

fix(rust): memory allocation in filtered spans

---

demo-iota/rust/Cargo.lock
demo-iota/rust/src/main.rs

Fixes the iota rust service to use the latest SDK since `Options` was added.

fix: rust iota service dep update

---

README.md

Adds links to the Honeycomb, Lightstep and other adapters recently added in the supported languages

chore: update support table in readme

---

go/trace_ctx.go

Avoid adding the dylibso_observe functions multiple times, fixes an issue we're running into in: https://github.com/bacalhau-project/bacalhau/pull/2971

cleanup: avoid initializing dylibso_observe module multiple times

---

go/trace_ctx.go
observe-api/go/observe_api.go

Updates the Go APIs to use the latest names. 
Also, without the new check and minimum default setting in `trace_ctx.go`, any custom setting to the observe trace config options without `ChannelBufferSize` would use its zero value (0), and would block the SDK from handling events.

fix: go sdk and api updates to latest

---

go/adapter.go

Resolves https://github.com/dylibso/wasm-practitioners-guide-to-observability/issues/11
Not extensively tested.

fix: go adapter, apply span tags and memory grow to current span instead of last span

---

demo-iota/rust/Cargo.lock
demo-iota/rust/Cargo.toml

Should fix https://app.northflank.com/t/dylibso-eng/project/iota/services/iota-web/builds/busy-oven-2446

fix: update iota's wasmtime to work with from observe sdk wasmtime

---

go/adapter/stdout/adapter.go
go/trace_ctx.go

fix(go): make sure metric and logs events are added to the current span
